apply plugin: 'com.gradleup.shadow'

apply from: "https://raw.githubusercontent.com/henkelmax/mod-gradle-scripts/${mod_gradle_script_version}/mod.gradle"

repositories {
    mavenCentral()
}

dependencies {
    implementation "io.netty:netty-handler:${netty_version}"
    implementation "io.netty:netty-buffer:${netty_version}"
    implementation "io.netty:netty-transport:${netty_version}"
    implementation "com.mojang:datafixerupper:${datafixerupper_version}"
    implementation "org.joml:joml:${joml_version}"
}
